#!/bin/bash
read name
echo "#include \"main.h\"
#include <ctype.h>

/**
 * _isupper - the function that check if character is uppercase.
 *
 * @c: the character.
 *
 * Return: 1 if uppercase , 0 if lowercase.
*/
" > $name

vi $name
