#!/bin/bash

read name
echo "#include \"main.h\"
#include <string.h>

/**
 * _strcat - the function that strcat two arrays
 *
 * @dest: the string one
 * @src:  the string 2
 *
 * Return: dest always
 */" > "$name"

vi $name
