#!bin/bash
read name
echo "#include <stdio.h>

/**
 * main - Entry point
 *
 * Description: A C program that prints with put function
 *
 * Return: Alawys 0 (Success)
*/
int main(void)
{
        return (0);
}
" > $name
vi $name
